worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream django_cluster {
        # Weighted Round Robin
        # We set max_fails=0 so Nginx never disables our servers dynamically.
        # This prevents Nginx from cutting off Server-Alpha when it returns a protective 503.
        server 127.0.0.1:8001 weight=5 max_fails=0 max_conns=1000;
        server 127.0.0.1:8002 weight=5 max_fails=0 max_conns=1000;
        server 127.0.0.1:8003 weight=5 max_fails=0 max_conns=1000;
    }

    server {
        listen 8080;

        # No timeout for heavy stress tests (matches our python timeout=None)
        proxy_read_timeout 3600;
        proxy_connect_timeout 30;
        proxy_send_timeout 3600;

        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }

        location / {
            proxy_pass http://django_cluster;
            
            # Route immediately to working servers on real connection errors,
            # but do NOT retry on 503/502 (let them pass through).
            proxy_next_upstream error timeout;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
